# Copyright (c) 2023, 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

title: "AI Transaction Monitoring Workload"
stackDescription: "This stack deploys the AI Transaction Monitoring Workload, a fully functional workload that allows customers to deploy an Automated Federated Learning Setup for GraphSAGE on Elliptic++ Dataset with Terraform and NVFlare." # github link could be added here once it exists 
description: "This stack deploys the AI Transaction Monitoring Workload, a fully functional workload that allows customers to deploy an Automated Federated Learning Setup for GraphSAGE on Elliptic++ Dataset with Terraform and NVFlare." # github link could be added here once it exists
schemaVersion: 1.1.0
version: "0.0.1"
locale: "en"

# URL of OCI Core Landing Zone logo icon used on Application Information tab.
# logoUrl: No current logo, can be added once made

variableGroups:
  - title: "General"
    variables:
      - "workload_name"
      - "workload_compartment_ocid"
      - "app_subnet_compartment_ocid"
      - "app_subnet_ocid"
      - "add_lb"
      - "lb_subnet_compartment_ocid"
      - "lb_subnet_ocid"

  - title: "Compute"
    variables:
      - "compute_shape"
      - "compute_boot_volume_size"
      - "compute_ssh_public_key"
      - "compute_availability_domain"
      - "compute_fault_domain"
      - "block_volume_size"

  - title: "Hidden Variables"
    variables:
      - "lb_policy"
      - "fingerprint"
      - "private_key_password"
      - "private_key_path"
      - "tenancy_ocid"
      - "user_ocid"
      - "region"


# ------------------------------------------------------
# ------------   General Vars   ------------------------
#-------------------------------------------------------

variables:

  workload_name:
    type: string
    title: "Workload Name"
    description: "Provide the name of the workload. This name is appended to resources to differentiate between similar workloads."
    required: true
    default: "FSI_TMS"

  workload_compartment_ocid:
    type: oci:identity:compartment:id
    title: "Workload Compartment OCID"
    description: "Choose the existing Workload Compartment. Resources will be deployed in this compartment."
    required: true

  app_subnet_compartment_ocid:
    type: oci:identity:compartment:id
    title: "App Subnet Compartment OCID"
    description: "Choose the compartment where the existing app subnet resides."
    required: true

  app_subnet_ocid:
    type: oci:core:subnet:id
    dependsOn:
      compartmentId: ${app_subnet_compartment_ocid}
    title: "App Subnet OCID"
    description: "Choose the existing App Subnet."
    required: true
  
  add_lb:
    type: boolean
    title: "Add a Load Balancer?"
    description: "Deploys an optional load balancer as well as a backend set."
    required: true
    default: false

  lb_subnet_compartment_ocid:
    type: oci:identity:compartment:id
    title: "Load Balancer Subnet Compartment OCID"
    description: "Choose the compartment where the existing load balancer subnet resides."
    required: true
    visible:
      eq:
        - ${add_lb}
        - true 

  lb_subnet_ocid:
    type: oci:core:subnet:id
    dependsOn:
      compartmentId: ${lb_subnet_compartment_ocid}
    title: "Load Balancer Subnet OCID"
    description: "Choose the existing Load Balancer Subnet."
    required: false
    visible:
      eq:
        - ${add_lb}
        - true 

# ------------------------------------------------------
# ------------   Compute Vars  -------------------------
#-------------------------------------------------------

  compute_shape:
    type: enum
    title: "Compute Shape"
    description: "Enter the GPU-based shape of the computer instance"
    required: false
    default: "VM.GPU.A10.1" 
    enum:
      - "VM.GPU.A10.1"
      - "VM.GPU.A10.2"
      - "VM.GPU.GU1.1"
      - "VM.GPU.GU1.2"
      - "VM.GPU2.1"
      - "VM.GPU3.1"
      - "VM.GPU3.2"
      - "VM.GPU3.4"
      - "BM.GPU4.8"
      - "BM.GPU.B4.8"
      - "BM.GPU.A100-v2.8"
      - "BM.GPU.H100.8"
      - "BM.GPU2.2"
      - "BM.GPU3.8"
      - "BM.GPU.T1.2"
      - "BM.GPU.A10.4"
      - "BM.GPU.T1-2.4"

  compute_boot_volume_size:
    type: integer
    title: "Compute Boot Volume Size"
    description: "Enter the Boot volume size (in GBs) of the compute instance"
    required: false
    default: 250

  compute_ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Compute SSH Public Key"
    description: "Enter the Public SSH Key used to access the compute instance."
    required: false

  compute_availability_domain:
    type: integer
    title: "Compute Availability Domain"
    description: "Enter the availability domain where the compute instance will be deployed."
    required: false
    default: 1

  compute_fault_domain:
    type: integer
    title: "Compute Fault Domain"
    description: "Enter the fault domain where the compute instance will be deployed."
    required: false
    default: 1

  block_volume_size:
    type: integer
    title: "Block Volume Size"
    description: "Enter the Block volume size (in GBs) to be attached to the compute instance."
    required: false
    default: 200

# ------------------------------------------------------
# ------------   Hidden Vars  --------------------------
#-------------------------------------------------------

  lb_policy:
    description: "The load balancing policy for distrubuting incoming traffic to backend servers."
    type: string
    default: "ROUND_ROBIN"
    visible: false

  fingerprint:
    visible: false

  private_key_password:
    visible: false

  private_key_path:
    visible: false

  tenancy_ocid:
    visible: false

  user_ocid:
    visible: false

  region:
    type: oci:identity:region:name
    required: true
    visible: false